In [3]:
import pandas as pd
from collections import OrderedDict

df = pd.read_csv("Dicc.csv", sep=";")

In [6]:
df = pd.DataFrame(OrderedDict([
    ('climate', ['Sunny', 'Snowy', 'Sunny', 'Rainy']),
    ('temperature', [13, 50, 30]),
    ('city', ['NYC', 'Montreal', 'Miami', 'NYC'])
]))

ValueError: All arrays must be of the same length

In [5]:
df

  climate  temperature      city
0   Sunny           13       NYC
1   Snowy           43  Montreal
2   Sunny           50     Miami
3   Rainy           30       NYC

In [9]:
COMPETENCIAS = pd.read_csv("competencias.csv", sep=",")

In [20]:
# rename columns en competencias
COMPETENCIAS.rename(
    columns={
        x[0]: x[1] for x in zip(COMPETENCIAS.columns[-23:], df.filter(regex="\d\.\d").columns)
    }
    )

,COMPETENCIAS AGRUPADAS,Unnamed: 1,1.1,1.2,1.3,1.4,1.5,2.1,2.2,2.3,...,4.2,4.3,5.1,5.2,5.3,6.1,6.2,6.3,6.4,6.5
0,Búsqueda y selección de contenidos o información,para la,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
1,Creación o modificación de contenido,para la,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN
2,"Protección de datos, gestión y compartición",en la,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
3,Proceso de Enseñanza-Aprendizaje,en la,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Evaluación, orientación y apoyo",para la,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Aprendizaje entre iguales,en el,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN
6,Aprendizaje autorregulado,en el,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN
7,Estrategias de Evaluación,en las,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Accesibilidad e inclusión,para la,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,1.0,1.0,1.0,NaN,NaN,1.0,1.0,NaN
9,Recursos para que el alumado desarrolle de for...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
10,Comunicación con el alumnado y/o familias,para la,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN

In [19]:
list(zip(COMPETENCIAS.columns[-23:], df.filter(regex="\d\.\d").columns))

[('Unnamed: 2', '1.1'),
 ('Unnamed: 3', '1.2'),
 ('Unnamed: 4', '1.3'),
 ('Unnamed: 5', '1.4'),
 ('Unnamed: 6', '1.5'),
 ('Unnamed: 7', '2.1'),
 ('Unnamed: 8', '2.2'),
 ('Unnamed: 9', '2.3'),
 ('Unnamed: 10', '3.1'),
 ('Unnamed: 11', '3.2'),
 ('Unnamed: 12', '3.3'),
 ('Unnamed: 13', '3.4'),
 ('Unnamed: 14', '4.1'),
 ('Unnamed: 15', '4.2'),
 ('Unnamed: 16', '4.3'),
 ('Unnamed: 17', '5.1'),
 ('Unnamed: 18', '5.2'),
 ('Unnamed: 19', '5.3'),
 ('Unnamed: 20', '6.1'),
 ('Unnamed: 21', '6.2'),
 ('Unnamed: 22', '6.3'),
 ('Unnamed: 23', '6.4'),
 ('Unnamed: 24', '6.5')]

In [15]:
COMPETENCIAS

,COMPETENCIAS AGRUPADAS,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,Búsqueda y selección de contenidos o información,para la,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
1,Creación o modificación de contenido,para la,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN
2,"Protección de datos, gestión y compartición",en la,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
3,Proceso de Enseñanza-Aprendizaje,en la,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Evaluación, orientación y apoyo",para la,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Aprendizaje entre iguales,en el,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN
6,Aprendizaje autorregulado,en el,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN
7,Estrategias de Evaluación,en las,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Accesibilidad e inclusión,para la,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,1.0,1.0,1.0,NaN,NaN,1.0,1.0,NaN
9,Recursos para que el alumado desarrolle de for...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
10,Comunicación con el alumnado y/o familias,para la,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN

In [7]:
df.filter(regex="1\.\d").columns

Index(['1.1', '1.2', '1.3', '1.4', '1.5'], dtype='object')

In [17]:
df.iloc[:, -23:] = df.filter(regex="\d\.\d").fillna(0).astype(int)

In [22]:
# Create this dict as an ordered dict
int_competencias = {
    1: "A1",
    2: "A2",
    3: "B1",
    4: "B2",
    5: "C1",
    6: "C2",
}

def competencias_form_int_to_str(x):
    print(int_competencias.get(x))
        
competencias_form_int_to_str(2)

A2

In [25]:
df.filter(regex="\d\.\d").fillna(0).astype(int).applymap(int_competencias.get).fillna("")

,1.1,1.2,1.3,1.4,1.5,2.1,2.2,2.3,3.1,3.2,...,4.2,4.3,5.1,5.2,5.3,6.1,6.2,6.3,6.4,6.5
0,A2,A1,,A1,A1,A1,,A1,,,...,,,,,,,,,,
1,A1,,,A1,A1,,,,A1,,...,A1,A1,,,,,,,,
2,A1,,,A1,A1,,,,A1,,...,A1,A1,,,,,,,,
3,,,,,,,,,,,...,,,,,,,,,A1,A1
4,,,,A1,,,A1,,A1,,...,,,A1,,A1,,,A1,,A1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,A1,A1,,A1,A1,,,,A1,,...,,,,,,,A1,,,
299,A1,,,A1,A1,,,,,,...,,,,,,,,,,
300,A1,,,A1,A1,,,,,,...,,,,,,,,,,
301,,,,A1,,,A1,,A1,,...,,,A1,,A1,,,A1,,A1
302,,,,A1,,,A2,,A1,,...,,,,,A1,,,A1,,A1

In [32]:
df["SINONIMOS"].fillna("").str.split(",").explode().str.strip()

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
298   NaN
299   NaN
300   NaN
301   NaN
302   NaN
Name: SINONIMOS, Length: 303, dtype: float64

In [33]:
df["SINONIMOS"].fillna("").apply(lambda x: x.split(","))

0      [ADIASWEB,  ADISWEB,  ABIASWEB,  ABISWEB,  ABI...
1                    [GESTION ACADEMICA,  GIR ACADEMICA]
2         [GESTION ACADEMICA,  SIGAD-,  SIGAD-ACADEMICA]
3                                                     []
4      [AUDCITY,  AUDACITI,  ADACITY,  edición de audio]
                             ...
298                                                   []
299                                                   []
300                                                   []
301                                                   []
302                                                   []
Name: SINONIMOS, Length: 303, dtype: object

In [36]:
df["bag_of_words"] = df[["PALABRA_CLAVE","SINONIMOS"]].fillna("").apply(lambda x: x[0].split(",") + x[1].split(",")[], axis=1)

In [47]:
# Select row if a word is in a list of words in a column
df["test"] = df["bag_of_words"].apply(lambda x: [x.strip() for x in x])

In [49]:
"SIGAD-" in df["test"][2]

True

In [52]:
# return a set of columns if a word is in a list of words in a column
df.loc[df["test"].apply(lambda x: "SIGAD-" in x), df.filter(regex="\d\.\d").columns]

,1.1,1.2,1.3,1.4,1.5,2.1,2.2,2.3,3.1,3.2,...,4.2,4.3,5.1,5.2,5.3,6.1,6.2,6.3,6.4,6.5
2,1,0,0,1,1,0,0,0,1,0,...,1,1,0,0,0,0,0,0,0,0

In [54]:
len(df)

303